version: "3"

services:
  serverless:
    container_name: serverless
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    volumes:
      - ./app:/app:delegated
    depends_on:
      local-questions-db:
        condition: service_healthy
    environment:
      - MONGO_CONNECTION_STRING=mongodb://local-questions-db:27017
    ports:
      - "3000:80"

  local-questions-db:
    container_name: local-questions-db
    image: mongo:latest
    volumes:
      - local-questions-db-data:/data/db
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD-SHELL", "pgrep mongod"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    command: mongod --quiet --logpath /dev/null

volumes:
  local-questions-db-data: